<a href="https://colab.research.google.com/github/suyogbastakoti/Ai-and-Ml-Module/blob/main/2407093_SuyogBastakoti_Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Worksheet 0**

**4.1 Exercise on Functions:**

**Task- 1:**

**Create a Python program that converts between different units of measurement.**

**• The program should:**
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:– Convert meters (m) to feet (ft).– Convert feet (ft) to meters (m).
2. Weight:– Convert kilograms (kg) to pounds (lbs).– Convert pounds (lbs) to kilograms (kg).
3. Volume:– Convert liters (L) to gallons (gal).– Convert gallons (gal) to liters (L)

In [2]:
def convert_units(conversion_type, value, direction):
    """
    Converts values between different units of measurement.

    Parameters:
    conversion_type (str): The type of conversion ('length', 'weight', 'volume').
    value (float): The numeric value to convert.
    direction (str): The conversion direction:
                     For length: 'm_to_ft' or 'ft_to_m'
                     For weight: 'kg_to_lbs' or 'lbs_to_kg'
                     For volume: 'l_to_gal' or 'gal_to_l'

    Returns:
    float: The converted value.
    """
    # Conversion factors
    if conversion_type == "length":
        if direction == "m_to_ft":
            return value * 3.28084
        elif direction == "ft_to_m":
            return value / 3.28084
    elif conversion_type == "weight":
        if direction == "kg_to_lbs":
            return value * 2.20462
        elif direction == "lbs_to_kg":
            return value / 2.20462
    elif conversion_type == "volume":
        if direction == "l_to_gal":
            return value * 0.264172
        elif direction == "gal_to_l":
            return value / 0.264172
    else:
        raise ValueError("Unsupported conversion type or direction.")

# Main program
print("Welcome to the Unit Converter!")

try:
    conversion_type = input("Choose conversion type (length, weight, volume): ").strip().lower()

    if conversion_type not in ["length", "weight", "volume"]:
        raise ValueError("Invalid conversion type selected.")

    value = float(input("Enter the value to convert: "))

    if conversion_type == "length":
        direction = input("Convert 'm_to_ft' or 'ft_to_m'?: ").strip().lower()
    elif conversion_type == "weight":
        direction = input("Convert 'kg_to_lbs' or 'lbs_to_kg'?: ").strip().lower()
    elif conversion_type == "volume":
        direction = input("Convert 'l_to_gal' or 'gal_to_l'?: ").strip().lower()

    result = convert_units(conversion_type, value, direction)
    print(f"Converted value: {result:.2f}")

except ValueError as ve:
    print(f"Error: {ve}")
except Exception as e:
    print(f"Unexpected error: {e}")

Welcome to the Unit Converter!
Choose conversion type (length, weight, volume): volume
Enter the value to convert: 20
Convert 'l_to_gal' or 'gal_to_l'?: l_to_gal
Converted value: 5.28


**Task- 2:**

**Create a Python program that performs various mathematical operations on a list of numbers.**

**• The Program should:**
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
18
6CS012
Worksheet- 0
Siman Giri
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, mini
mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [3]:
# Function to calculate sum
def find_sum(numbers):
    """
    Returns the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Sum of the numbers.
    """
    return sum(numbers)


# Function to calculate average
def find_average(numbers):
    """
    Returns the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Average of the numbers.
    """
    return sum(numbers) / len(numbers)


# Function to find maximum
def find_max(numbers):
    """
    Returns the maximum value from a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Maximum value.
    """
    return max(numbers)


# Function to find minimum
def find_min(numbers):
    """
    Returns the minimum value from a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Minimum value.
    """
    return min(numbers)


print("Math Operations on a List of Numbers")

try:
    # Ask user for operation
    operation = input("Choose operation (sum, average, max, min): ").lower()

    # Ask user for numbers
    user_input = input("Enter numbers separated by spaces: ")

    # Convert input into a list of numbers
    numbers = [float(num) for num in user_input.split()]

    if len(numbers) == 0:
        raise ValueError("List cannot be empty")

    # Perform selected operation
    if operation == "sum":
        result = find_sum(numbers)
    elif operation == "average":
        result = find_average(numbers)
    elif operation == "max":
        result = find_max(numbers)
    elif operation == "min":
        result = find_min(numbers)
    else:
        raise ValueError("Invalid operation selected")

    print("Result:", result)

except ValueError:
    print("Error: Please enter valid numbers and operation.")
except Exception as e:
    print("Unexpected error:", e)

Math Operations on a List of Numbers
Choose operation (sum, average, max, min): average
Enter numbers separated by spaces: 10 20 30 40
Result: 25.0


**4.2 Exercise on List Manipulation:**

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:– Define a function extract
every
other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].
2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:– Define a function get
sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].
3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:– Define a function reverse
slicing.
list(lst) that takes a list lst and returns a reversed list using– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].
19
6CS012
Worksheet- 0
Siman Giri
4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:– Defineafunction remove
first
last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].
5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:– Define a function get
first
n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].
6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:– Define a function get
last
n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].
7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:– Define a function reverse
skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].


In [4]:
# 1. Extract Every Other Element
def extract_every_other(lst):
    """
    Returns every other element from the list starting from the first element.
    """
    return lst[::2]


# 2. Slice a Sublist (inclusive of end)
def get_sublist(lst, start, end):
    """
    Returns a sublist from index 'start' to 'end' (inclusive).
    """
    return lst[start:end+1]


# 3. Reverse a List Using Slicing
def reverse_list(lst):
    """
    Returns the reversed version of the list using slicing.
    """
    return lst[::-1]


# 4. Remove the First and Last Elements
def remove_first_last(lst):
    """
    Removes the first and last elements from the list.
    """
    return lst[1:-1]


# 5. Get the First n Elements
def get_first_n(lst, n):
    """
    Returns the first n elements of the list.
    """
    return lst[:n]


# 6. Extract the Last n Elements
def get_last_n(lst, n):
    """
    Returns the last n elements of the list.
    """
    return lst[-n:]


# 7. Extract Elements in Reverse Order Skipping One
def reverse_skip(lst):
    """
    Returns elements starting from the second-to-last element,
    moving backwards while skipping one element each time.
    """
    return lst[-2::-2]


# Example list
numbers = [1, 2, 3, 4, 5, 6]

print("Original List:", numbers)

print("1.", extract_every_other(numbers))
print("2.", get_sublist(numbers, 2, 4))
print("3.", reverse_list(numbers))
print("4.", remove_first_last(numbers))
print("5.", get_first_n(numbers, 3))
print("6.", get_last_n(numbers, 2))
print("7.", reverse_skip(numbers))

Original List: [1, 2, 3, 4, 5, 6]
1. [1, 3, 5]
2. [3, 4, 5]
3. [6, 5, 4, 3, 2, 1]
4. [2, 3, 4, 5]
5. [1, 2, 3]
6. [5, 6]
7. [5, 3, 1]


**4.3 Exercise on Nested List:**

1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].
2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:– Define a function access
nested
element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.
3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:– Define a function sum
nested(lst) that takes a nested list lst and returns the sum of all
the elements.– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.
4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:– Define a function remove
element(lst, elem) that removes elem from lst and returns the
modified list.– Example: Fortheinput lst = [[1, 2], [3, 2], [4, 5]]andelem = 2,theoutputshould
be [[1], [3], [4, 5]].
5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:– Define a function find
element.
max(lst) that takes a nested list lst and returns the maximum– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.
21
6CS012
Worksheet- 0
Siman Giri
6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:– Define a function count
occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.– Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,theoutputshould
be 3.
7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:– Define a function deep
flatten(lst) that takes a deeply nested list lst and returns a single
f
lattened list.– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].
8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:– Define a function average
of all the elements.
nested(lst) that takes a nested list lst and returns the average– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.


In [5]:
# 1. Flatten a Nested List
def flatten(lst):
    """
    Flattens a nested list into a single list (one level).
    """
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)
    return result


# 2. Access Element from Nested List
def access_nested_element(lst, indices):
    """
    Access an element from a nested list using a list of indices.
    """
    element = lst
    for i in indices:
        element = element[i]
    return element


# 3. Sum of All Elements in Nested List (any depth)
def sum_nested(lst):
    """
    Returns the sum of all numbers in a nested list regardless of depth.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


# 4. Remove Specific Element from Nested List
def remove_element(lst, elem):
    """
    Removes all occurrences of elem from a nested list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result


# 5. Find Maximum Element in Nested List
def find_max(lst):
    """
    Finds the maximum element in a nested list regardless of depth.
    """
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val


# 6. Count Occurrences in Nested List
def count_occurrences(lst, elem):
    """
    Counts how many times elem appears in a nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


# 7. Deep Flatten (any depth)
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result


# 8. Average of Nested List
def average_nested(lst):
    """
    Returns the average of all numbers in a nested list.
    """
    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list)


# ---------------------------
# Example Runs
# ---------------------------

print(flatten([[1,2],[3,4],[5]]))

lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst,[1,2]))

print(sum_nested([[1,2],[3,[4,5]],6]))

print(remove_element([[1,2],[3,2],[4,5]],2))

print(find_max([[1,2],[3,[4,5]],6]))

print(count_occurrences([[1,2],[2,3],[2,4]],2))

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

print(average_nested([[1,2],[3,4],[5,6]]))

[1, 2, 3, 4, 5]
6
21
[[1], [3], [4, 5]]
6
3
[1, 2, 3, 4, 5, 6, 7, 8]
3.5


**10 To- Do- NumPy**


**Please complete all the problems listed below:**

**10.1 Basic Vector and Matrix Operation with Numpy.**

**Problem- 1: Array Creation:**

**Complete the following Tasks:**

1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [6]:
import numpy as np

In [7]:
# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2,2))
print("Empty Array (2x2):")
print(empty_array)


# 2. Initialize an all ones array with size 4x2
ones_array = np.ones((4,2))
print("\nOnes Array (4x2):")
print(ones_array)


# 3. Create a new array filled with a specific value
full_array = np.full((3,3), 7)
print("\nArray filled with 7:")
print(full_array)


# 4. Return a new array of zeros with same shape as given array
zeros_like_array = np.zeros_like(full_array)
print("\nZeros Like Array:")
print(zeros_like_array)


# 5. Return a new array of ones with same shape as given array
ones_like_array = np.ones_like(full_array)
print("\nOnes Like Array:")
print(ones_like_array)


# 6. Convert a Python list to a NumPy array
new_list = [1,2,3,4]
numpy_array = np.array(new_list)

print("\nNumPy Array from List:")
print(numpy_array)

Empty Array (2x2):
[[2.1359171e-315 0.0000000e+000]
 [5.7889790e-317 5.7892162e-317]]

Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones Like Array:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

NumPy Array from List:
[1 2 3 4]


**Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:**

**Complete the following tasks:**

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [8]:
#1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("Array from 10 to 49:")
print(arr1)

Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#2. Create a 3×3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3,3)
print("\n3x3 Matrix from 0 to 8:")
print(arr2)


3x3 Matrix from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#3. Create a 3×3 identity matrix
identity = np.eye(3)
print("\nIdentity Matrix:")
print(identity)


Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#4. Create a random array of size 30 and find the mean
random_arr = np.random.random(30)
mean_value = random_arr.mean()

print("\nRandom Array:")
print(random_arr)
print("Mean:", mean_value)


Random Array:
[0.6931238  0.08878223 0.50516486 0.61734854 0.66951607 0.36978896
 0.41595392 0.17505668 0.64894977 0.19370305 0.15739732 0.42867035
 0.05358243 0.66616836 0.12653828 0.82804116 0.697154   0.54585675
 0.74722654 0.0273124  0.57627121 0.23623431 0.32038521 0.68244541
 0.01694012 0.0287958  0.82288942 0.7376266  0.68408695 0.32439739]
Mean: 0.4361802633072715


In [12]:
#5. Create a 10×10 array with random values and find min and max
arr5 = np.random.random((10,10))

print("\n10x10 Random Array:")
print(arr5)
print("Minimum:", arr5.min())
print("Maximum:", arr5.max())


10x10 Random Array:
[[0.71101183 0.00683841 0.11517526 0.22754075 0.12049076 0.70598455
  0.58137853 0.51704865 0.70935682 0.90671153]
 [0.69035776 0.56144732 0.1414199  0.02589242 0.76805516 0.80429887
  0.39720904 0.630578   0.33707268 0.49385697]
 [0.6369336  0.73438205 0.09614104 0.90316923 0.87412665 0.98183643
  0.52860009 0.12424641 0.71318159 0.29388241]
 [0.25451149 0.34202055 0.38291036 0.67969522 0.27376154 0.70827748
  0.94256803 0.69642583 0.06356285 0.9639553 ]
 [0.12949704 0.63738088 0.72960428 0.70769728 0.56058938 0.30939406
  0.18641774 0.36072653 0.07327819 0.68808805]
 [0.91565304 0.95859663 0.18230299 0.50596826 0.72827934 0.23722937
  0.77482057 0.44147993 0.30401476 0.10008201]
 [0.37318182 0.16031359 0.27222473 0.67907447 0.61097307 0.40132053
  0.71530969 0.06033432 0.89115675 0.53967568]
 [0.82369425 0.04146594 0.59813855 0.51792724 0.29827086 0.94979256
  0.05035444 0.94137541 0.54931293 0.84660919]
 [0.81914448 0.79390728 0.87260817 0.4176038  0.6556328  0.

In [13]:
#6. Create a zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1   # index starts from 0

print("\nZero Array with 5th element replaced:")
print(arr6)


Zero Array with 5th element replaced:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
#7. Reverse an array
arr7 = np.array([1,2,0,0,4,0])
reversed_arr = arr7[::-1]

print("\nReversed Array:")
print(reversed_arr)


Reversed Array:
[0 4 0 0 2 1]


In [15]:
#8. Create a 2D array with 1 on border and 0 inside
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] = 0

print("\nBorder Array:")
print(arr8)


Border Array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
#9. Create an 8×8 matrix with checkerboard pattern
checkerboard = np.zeros((8,8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print("\nCheckerboard Pattern:")
print(checkerboard)


Checkerboard Pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem- 3: Array Operations:**

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

**First defining the arrays.**

In [19]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

In [20]:
#1. Add the two arrays
add_result = x + y
print("Addition of x and y:")
print(add_result)

Addition of x and y:
[[ 6  8]
 [10 13]]


In [21]:
#2. Subtract the two arrays
sub_result = x - y
print("\nSubtraction of x and y:")
print(sub_result)


Subtraction of x and y:
[[-4 -4]
 [-4 -3]]


In [22]:
#3. Multiply the array with any integer
mul_result = x * 3
print("\nArray x multiplied by 3:")
print(mul_result)


Array x multiplied by 3:
[[ 3  6]
 [ 9 15]]


In [24]:
#4. Find the square of each element
square_result = x ** 2
print("\nSquare of each element of x:")
print(square_result)


Square of each element of x:
[[ 1  4]
 [ 9 25]]


In [27]:
#5. Dot Product
#for v and w
dot_vw = np.dot(v,w)
print("\nDot product of v and w:")
print(dot_vw)


Dot product of v and w:
219


In [26]:
#for x and v
dot_xv = np.dot(x,v)
print("\nDot product of x and v:")
print(dot_xv)


Dot product of x and v:
[29 77]


In [30]:

# Calculate dot product
dot_xy = np.dot(x, y)

print("\nDot product of x and y:")
print(dot_xy)


Dot product of x and y:
[[19 22]
 [50 58]]


In [31]:
#6. Concatenate arrays
#Concatenate x and y along rows
concat_xy = np.concatenate((x,y), axis=0)
print("\nConcatenate x and y along rows:")
print(concat_xy)


Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [32]:
#Concatenate v and w along columns
concat_vw = np.vstack((v,w)).T
print("\nConcatenate v and w along columns:")
print(concat_vw)


Concatenate v and w along columns:
[[ 9 11]
 [10 12]]


In [33]:
#7. Concatenate x and v
np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Explanation**

This gives an error because:

x is a 2D array → shape (2,2)

v is a 1D array → shape (2,)

NumPy cannot concatenate arrays with different dimensions.

To fix this, we must reshape v into a 2D array.

In [34]:
v2 = v.reshape(1,2)
fixed_concat = np.concatenate((x,v2), axis=0)

print("\nConcatenation after reshaping v:")
print(fixed_concat)


Concatenation after reshaping v:
[[ 1  2]
 [ 3  5]
 [ 9 10]]


**Problem- 4: Matrix Operations:**

• For the following arrays:
A = np.array([[3,4],[7,8]]) and

B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB̸ = BA.
3. Prove (AB)T = BTAT.
• Solve the following system of Linear equation using Inverse Methods.
2x −3y+z =−1
x −y+2z =−3
3x +y−z =9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func
tion of Numpy}

In [35]:
#First import NumPy and define the matrices.
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

Matrix A:
[[3 4]
 [7 8]]

Matrix B:
[[5 3]
 [2 1]]


In [37]:
#1. Prove 𝐴⋅𝐴−1=𝐼A⋅A−1=I
# Find inverse of A
A_inv = np.linalg.inv(A)

print("Inverse of A:")
print(A_inv)

# Multiply A and A inverse
result = np.dot(A, A_inv)

print("\nA * A^-1 :")
print(np.round(result,5))


Inverse of A:
[[-2.    1.  ]
 [ 1.75 -0.75]]

A * A^-1 :
[[1. 0.]
 [0. 1.]]


**The result shows that multiplying a matrix by its inverse gives the identity matrix.**

In [38]:
#2. Prove 𝐴𝐵≠𝐵A
AB = np.dot(A,B)
BA = np.dot(B,A)

print("\nAB =")
print(AB)

print("\nBA =")
print(BA)



AB =
[[23 13]
 [51 29]]

BA =
[[36 44]
 [13 16]]


In [39]:
#3. Prove (𝐴𝐵)𝑇=BTAT
# Left side
left = np.transpose(np.dot(A,B))

# Right side
right = np.dot(np.transpose(B), np.transpose(A))

print("\n(AB)^T =")
print(left)

print("\nB^T A^T =")
print(right)


(AB)^T =
[[23 51]
 [13 29]]

B^T A^T =
[[23 51]
 [13 29]]


Both outputs will be the same, proving:

**(𝐴𝐵)𝑇=BTAT**

**Solve Linear Equations using Matrix Form**

In [40]:
#Given equations:

# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Matrix form:

# 𝐴𝑋 = B

# Where:

# A = coefficient matrix
# X = [x y z]
# B = constant matrix

#Step 1: Create matrices
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

In [41]:
#Solve using Inverse Method
A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("\nSolution (x, y, z):")
print(X)


Solution (x, y, z):
[ 2.  1. -2.]


So,

x = 2
y = 1
z = -2

**Summary of NumPy Linear Algebra Functions Used**

Function:
np.linalg.inv()

Purpose: Matrix inverse

Function: np.dot()

Purpose: Matrix multiplication

Function: np.transpose()

Purpose: Matrix transpose  

Function: np.linalg

Purpose: Linear algebra module

**10.2 Experiment: How Fast is Numpy?**
**In this exercise, you will compare the performance and implementation of operations using plain Python**
**lists (arrays) and NumPy arrays.**

**Follow the instructions:**

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea
sure and print the time taken for this operation.
• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation

In [42]:
#importing neccessary libraries
import numpy as np
import time

In [43]:
# 1. Element-wise Addition
size = 1_000_000

# Python lists
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
list_add = [a + b for a, b in zip(list1, list2)]
end = time.time()
print("Python List Addition Time:", round(end-start, 5), "seconds")

# NumPy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
np_add = arr1 + arr2
end = time.time()
print("NumPy Array Addition Time:", round(end-start, 5), "seconds")

Python List Addition Time: 0.04412 seconds
NumPy Array Addition Time: 0.00202 seconds


In [44]:
# 2. Element-wise Multiplication
# ---------------------------

# Python lists
start = time.time()
list_mul = [a * b for a, b in zip(list1, list2)]
end = time.time()
print("\nPython List Multiplication Time:", round(end-start, 5), "seconds")

# NumPy arrays
start = time.time()
np_mul = arr1 * arr2
end = time.time()
print("NumPy Array Multiplication Time:", round(end-start, 5), "seconds")


Python List Multiplication Time: 0.04946 seconds
NumPy Array Multiplication Time: 0.00281 seconds


In [46]:
# 3. Dot Product

# Python lists
start = time.time()
dot_list = sum(a*b for a,b in zip(list1,list2))
end = time.time()
print("\nPython List Dot Product Time:", round(end-start, 5), "seconds")

# NumPy arrays
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print("NumPy Array Dot Product Time:", round(end-start, 5), "seconds")


Python List Dot Product Time: 0.18425 seconds
NumPy Array Dot Product Time: 0.00235 seconds


In [49]:
#4. Matrix Multiplication
# ---------------------------

# For Python lists, we will use smaller size to avoid freezing
matrix_size = 300  # Use 300 instead of 1000 to keep Colab safe

# Python lists
mat1 = [[i+j for j in range(matrix_size)] for i in range(matrix_size)]
mat2 = [[i-j for j in range(matrix_size)] for i in range(matrix_size)]

start = time.time()
# naive Python matrix multiplication
result = [[sum(a*b for a,b in zip(row,col)) for col in zip(*mat2)] for row in mat1]
end = time.time()
print("\nPython List Matrix Multiplication Time (300x300):", round(end-start, 5), "seconds")

# NumPy arrays
mat_np1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
mat_np2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

start = time.time()
np_result = np.dot(mat_np1, mat_np2)
end = time.time()
print("NumPy Array Matrix Multiplication Time (300x300):", round(end-start, 5), "seconds")


Python List Matrix Multiplication Time (300x300): 1.81986 seconds
NumPy Array Matrix Multiplication Time (300x300): 0.02482 seconds


**Summary:**

**From this experiment, we can see a huge difference in performance between plain Python lists and NumPy arrays:**

Element-wise operations (addition and multiplication) are much faster with NumPy, even for large arrays of 1,000,000 elements.

Python lists use slow Python loops, while NumPy uses optimized C/Fortran routines internally.

Dot product calculations also show that NumPy is orders of magnitude faster than plain Python lists.

Matrix multiplication highlights the biggest difference:

Python lists take several minutes for large matrices, and sometimes can even freeze the notebook.

NumPy performs the same operation in fractions of a second, even for 1000×1000 matrices.

Reason: NumPy arrays are contiguous blocks of memory, support vectorized operations, and use highly optimized linear algebra libraries like BLAS and LAPACK. Python lists, on the other hand, are high-level objects and not optimized for numerical computations.

**Overall:**

This experiment clearly demonstrates that for numerical computations, NumPy is far more efficient and practical than Python lists, making it the standard choice for data analysis, scientific computing, and machine learning tasks.